apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component1
  namespace: managed
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: pullspec1
        name: container-image
        resources: {}
status: {}
